use_frameworks!

platform :ios, '8.0'

target 'ZSNetworking_Example' do
  pod 'ZSNetworking', :path => '../'

  target 'ZSNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
